### ISSUE TITLE
Mouse/Keyboard Template - CapLock

### ISSUE THREAD

**Issue by Soupy51** [ThomasBott/O-MEGA#1]
Hey Sem; 

The Shift and CapLock Keys are inoperative while Hotkey Mode is active using Android on-screen keyboard.

**Comment by ThomasBott** [comment]
Hi Soupy51,
this is the expected behavior. The hotkey mode is intended to send hotkeys/ key combinations only and pressing the shift key on the Android keyboard doesn't die fire an event the website could catch (as far as I know). If you actually want to send a combination including the shift key, you need to choose that key from the list on the left hand side.
